/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QuanLiSinhVien.View.DiemUI;

import QuanLiSinhVien.Model.Diem;
import QuanLiSinhVien.Service.DiemService;
import QuanLiSinhVien.View.Home;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sonlanggtu
 */
public class ListDiemFrame extends javax.swing.JFrame {

    DiemService diemService;
    DefaultTableModel defaultTableModel;

    /**
     * Creates new form ListDiemFrame
     */
    public ListDiemFrame() {
        initComponents();
        diemService = new DiemService();

        defaultTableModel = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        diemTable.setModel(defaultTableModel);
        defaultTableModel.addColumn("MaSV");
        defaultTableModel.addColumn("MaMH");
        defaultTableModel.addColumn("HocKy");
        defaultTableModel.addColumn("DiemLan1");
        defaultTableModel.addColumn("DiemLan2");
        SetTableData(diemService.GetAllDiem());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnaddDiem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        diemTable = new javax.swing.JTable();
        btnModifle = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lí thông tin sinh viên");

        btnaddDiem.setText("Thêm mới");
        btnaddDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddDiemActionPerformed(evt);
            }
        });

        diemTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        diemTable.setAlignmentX(1.0F);
        diemTable.setAlignmentY(1.0F);
        diemTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        diemTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        diemTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(diemTable);

        btnModifle.setText("Sửa");
        btnModifle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifleActionPerformed(evt);
            }
        });

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnDelete.setText("Xóa");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jButton1.setText("Trở về Trang Chủ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 953, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnaddDiem)
                        .addGap(48, 48, 48)
                        .addComponent(btnModifle, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRefresh)
                        .addGap(63, 63, 63)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnModifle, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                        .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                        .addComponent(btnRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                    .addComponent(btnaddDiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnaddDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddDiemActionPerformed
        new ThemDiemFrame().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnaddDiemActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed

        defaultTableModel.setRowCount(0);
        SetTableData(diemService.GetAllDiem());
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int row = diemTable.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(ListDiemFrame.this, "Vui lòng chọn bản ghi trước", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } else {
            int confirm = JOptionPane.showConfirmDialog(ListDiemFrame.this, "Bạn có chắc chắn xóa bản ghi này ?");
            if (confirm == JOptionPane.YES_OPTION) {
                   String GetMaSV =  String.valueOf(diemTable.getValueAt(row, 0));
                   String GetMaMH = String.valueOf(diemTable.getValueAt(row, 1));
                   String GetHocki =  String.valueOf(diemTable.getValueAt(row, 2));
                   diemService.DeleteDiem(GetMaSV, GetMaMH, Integer.valueOf(GetHocki));
                   
                   defaultTableModel.setRowCount(0);
                   SetTableData(diemService.GetAllDiem());
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnModifleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifleActionPerformed
         int row = diemTable.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(ListDiemFrame.this, "Vui lòng chọn bản ghi trước", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } else {
            int confirm = JOptionPane.showConfirmDialog(ListDiemFrame.this, "Bạn có chắc chắn muốn sửa bản ghi này ?");
            if (confirm == JOptionPane.YES_OPTION) {
                   String GetMaSV =  String.valueOf(diemTable.getValueAt(row, 0));
                   String GetMaMH = String.valueOf(diemTable.getValueAt(row, 1));
                   String GetHocki =  String.valueOf(diemTable.getValueAt(row, 2));
                new EditDiemFrame(GetMaSV, GetMaMH, Integer.valueOf(GetHocki)).setVisible(true);
                setVisible(false);
            }
        }
    }//GEN-LAST:event_btnModifleActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Home().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void SetTableData(List<Diem> diem) {
        for (Diem diemsql : diem) {
            defaultTableModel.addRow(new Object[]{diemsql.GetMaSV(), diemsql.GetMaMH(), diemsql.GetHocKy(), diemsql.GetDiemLan1(), diemsql.GetDiemLan2()});
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListDiemFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListDiemFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListDiemFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListDiemFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListDiemFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnModifle;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnaddDiem;
    private javax.swing.JTable diemTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
