/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QuanLiSinhVien.View.LopUI;

import QuanLiSinhVien.Model.Lop;
import QuanLiSinhVien.Service.LopService;
import QuanLiSinhVien.View.Home;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sonlanggtu
 */
public class ListLopFrame extends javax.swing.JFrame {
    
    Lop lop;
    LopService lopService;
    DefaultTableModel defaultTableModel;
    /**
     * Creates new form ListLopFrame
     */
    public ListLopFrame() {
        initComponents();
        lop = new Lop();
        lopService = new LopService();
        
        defaultTableModel = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        LopTable.setModel(defaultTableModel);
        defaultTableModel.addColumn("MaLop");
        defaultTableModel.addColumn("TenLop");
        defaultTableModel.addColumn("MaKhoa");
        defaultTableModel.addColumn("MaHeDT");
        defaultTableModel.addColumn("MaKhoaHoc");
        SetTableData(lopService.GetAllLop());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnModifle = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnaddMonHoc = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        LopTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lí lớp học");

        btnModifle.setText("Sửa");
        btnModifle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifleActionPerformed(evt);
            }
        });

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnDelete.setText("Xóa");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jButton1.setText("Trở về Trang Chủ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnaddMonHoc.setText("Thêm mới");
        btnaddMonHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddMonHocActionPerformed(evt);
            }
        });

        LopTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        LopTable.setToolTipText("");
        LopTable.setAlignmentX(1.0F);
        LopTable.setAlignmentY(1.0F);
        LopTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(LopTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 994, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnaddMonHoc)
                .addGap(48, 48, 48)
                .addComponent(btnModifle, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRefresh)
                .addGap(63, 63, 63)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnModifle, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                        .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                        .addComponent(btnRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                    .addComponent(btnaddMonHoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModifleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifleActionPerformed
        int row = LopTable.getSelectedRow();
        if (row == -1)
        {
            JOptionPane.showMessageDialog(ListLopFrame.this, "Vui lòng chọn bản ghi trước", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            int confirm = JOptionPane.showConfirmDialog(ListLopFrame.this, "Bạn có chắc chắn muốn sửa bản ghi này ?");
            if (confirm == JOptionPane.YES_OPTION) {
                String GetMaLop =  String.valueOf(LopTable.getValueAt(row, 0));
                new EditLopFrame(GetMaLop).setVisible(true);
                setVisible(false);
            }
        }
    }//GEN-LAST:event_btnModifleActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed

        defaultTableModel.setRowCount(0);
        SetTableData(lopService.GetAllLop());
    }//GEN-LAST:event_btnRefreshActionPerformed
    private void SetTableData(List<Lop> listlop)
    {
        for (Lop lop : listlop) {
            defaultTableModel.addRow(new Object[]{lop.GetMaLop(), lop.GetTenLop(), lop.GetMaKhoa(), lop.GetMaHeDT(), lop.GetMaKhoaHoc()});
        }
    }
    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int row = LopTable.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(ListLopFrame.this, "Vui lòng chọn bản ghi trước", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } else {
            int confirm = JOptionPane.showConfirmDialog(ListLopFrame.this, "Bạn có chắc chắn xóa bản ghi này ?");
            if (confirm == JOptionPane.YES_OPTION) {
                String GetMalop =  String.valueOf(LopTable.getValueAt(row, 0));
                lopService.DelLop(GetMalop);

                defaultTableModel.setRowCount(0);
                SetTableData(lopService.GetAllLop());
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Home().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnaddMonHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddMonHocActionPerformed
        new AddLopFrame().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnaddMonHocActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListLopFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListLopFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListLopFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListLopFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListLopFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable LopTable;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnModifle;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnaddMonHoc;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
