/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QuanLiSinhVien.View.MonHocUI;

import QuanLiSinhVien.Model.MonHoc;
import QuanLiSinhVien.Model.SinhVien;
import QuanLiSinhVien.Service.MonHocService;
import QuanLiSinhVien.Service.SinhVienService;
import QuanLiSinhVien.View.Home;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sonlanggtu
 */
public class ListMonHocFrame extends javax.swing.JFrame 

{
    
    DefaultTableModel defaultTableModel;
    MonHocService monHocService;
    MonHoc monHoc;
    /**
     * Creates new form ListMonHocFrame
     */
    public ListMonHocFrame() {
        monHoc = new MonHoc();
        monHocService = new MonHocService();
        initComponents();
        

        defaultTableModel = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        monHocTable.setModel(defaultTableModel);
        defaultTableModel.addColumn("MaSV");
        defaultTableModel.addColumn("TenSV");
        defaultTableModel.addColumn("GioiTinh");


        SetTableData(monHocService.GetAllMonHoc());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRefresh = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnaddMonHoc = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        monHocTable = new javax.swing.JTable();
        btnModifle = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lí môn học");

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnDelete.setText("Xóa");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jButton1.setText("Trở về Trang Chủ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnaddMonHoc.setText("Thêm mới");
        btnaddMonHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddMonHocActionPerformed(evt);
            }
        });

        monHocTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        monHocTable.setToolTipText("");
        monHocTable.setAlignmentX(1.0F);
        monHocTable.setAlignmentY(1.0F);
        monHocTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(monHocTable);

        btnModifle.setText("Sửa");
        btnModifle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 994, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnaddMonHoc)
                .addGap(48, 48, 48)
                .addComponent(btnModifle, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRefresh)
                .addGap(63, 63, 63)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnModifle, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                        .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                        .addComponent(btnRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                    .addComponent(btnaddMonHoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed

        defaultTableModel.setRowCount(0);
        SetTableData(monHocService.GetAllMonHoc());
    }//GEN-LAST:event_btnRefreshActionPerformed
    
    private void SetTableData(List<MonHoc> listMonHoc)
    {
        for (MonHoc monHoc : listMonHoc) {
            defaultTableModel.addRow(new Object[]{monHoc.GetMaMH(),monHoc.GetTenMH(), monHoc.GetSoTrinh()});
        }
    }
    
    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int row = monHocTable.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(ListMonHocFrame.this, "Vui lòng chọn bản ghi trước", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } else {
            int confirm = JOptionPane.showConfirmDialog(ListMonHocFrame.this, "Bạn có chắc chắn xóa bản ghi này ?");
            if (confirm == JOptionPane.YES_OPTION) {
                String GetMaMH =  String.valueOf(monHocTable.getValueAt(row, 0));
                monHocService.DelSinhVien(GetMaMH);

                defaultTableModel.setRowCount(0);
                SetTableData(monHocService.GetAllMonHoc());
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Home().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnaddMonHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddMonHocActionPerformed
        new AddMonHocFrame().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnaddMonHocActionPerformed

    private void btnModifleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifleActionPerformed
        int row = monHocTable.getSelectedRow();
        if (row == -1)
        {
            JOptionPane.showMessageDialog(ListMonHocFrame.this, "Vui lòng chọn bản ghi trước", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } 
        else
        {
            int confirm = JOptionPane.showConfirmDialog(ListMonHocFrame.this, "Bạn có chắc chắn muốn sửa bản ghi này ?");
            if (confirm == JOptionPane.YES_OPTION) {
                String GetMaMH =  String.valueOf(monHocTable.getValueAt(row, 0));
                new EditMonHocFrame(GetMaMH).setVisible(true);
                setVisible(false);
            }
        }
    }//GEN-LAST:event_btnModifleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListMonHocFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListMonHocFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListMonHocFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListMonHocFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ListMonHocFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnModifle;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnaddMonHoc;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable monHocTable;
    // End of variables declaration//GEN-END:variables
}
